name: haml
author: Kevin Moore <kevin@thinkpixellab.com>
homepage: https://github.com/kevmoo/haml.dart
environment:
  sdk: '>=0.4.7+1'
dependencies:
  bot: '>=0.16.3+1'
  bot_io: '>=0.20.0-dev'
  js: '>=0.0.22'
  logging: '>=0.4.5+1'
  meta: '>=0.4.5+1'
  pathos: '>=0.4.5+1'
  petitparser: '>=0.2.5+m4'
dev_dependencies:
  browser: '>=0.5.0+1'
  hop: '>=0.20.0'
